version: '3'
services:
  node-app:
    build: 
      # location of the dockerfile
      context: .
      # here we set argument NODE_ENV for dockerfile
      args:
        NODE_ENV: development
    # we need volumes to have persistent data
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
