version: '3'
services:
  node-app:
    build:
      # location of the dockerfile
      context: .
      # here we set argument NODE_ENV for dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
