version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      # location of the dockerfile
      context: .
      # here we set argument NODE_ENV for dockerfile
      args:
        NODE_ENV: development
    # we need volumes to have persistent data
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=docker_mongo
      - MONGO_PASSWORD=password
    command: npm run dev
  mongo:
    # see documentation on docker, the following is needed
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker_mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
